document.write('<div id="u_skip"><!-- skip navigation -->');
document.write('	<dl>');
document.write('		<dt class="blind">바로가기 메뉴</dt>');
document.write('		<dd><a href="#container">본문으로 바로가기</a></dd>');
document.write('	</dl>');
document.write('</div><!-- //skip navigation -->');
document.write('<header class="header_top v2"><!-- header -->');
document.write('	<div class="header_inner">');
document.write('		<h1 class="blind">메인메뉴 선택</h1>');
document.write('		<div class="slctbox">');
document.write('			<span class="txt">고등 참고서</span><span class="btn_slct"></span>');
document.write('			<label for="search" class="screen_out">검색분류선택</label>');
document.write('			<select id="search">');
document.write('				<option>고등 참고서</option>');
document.write('				<option>중등 참고서</option>');
document.write('				<option>초등 참고서</option>');
document.write('				<option>마이씽/마이쿠폰</option>');
document.write('			</select>');
document.write('		</div>');
document.write('		<p class="loc_totalmenue"><a href="#none" class="btn btn_menu">전체메뉴</a></p>');
document.write('		<p class="loc_home"><a href="#none" class="btn btn_home">HOME</a></p>');
document.write('	</div>');
document.write('	<div class="group_totalmenu"><!-- 전체메뉴 -->');
document.write('		<!-- 로그인 전 -->');
document.write('		<div class="group_lft_header">');
document.write('			<a href="#" class="btn_white"><span class="ico ico_key"></span>로그인</a><a href="#" class="btn_white"><span class="ico ico_join"></span>회원가입</a>');
document.write('		</div>');
document.write('		<!-- //로그인 전>');
document.write('		<!-- 로그인 후 -->');
document.write('		<!-- div class="group_lft_header v2">');
document.write('			<span class="ico ico_logout"></span><strong>홍길동</strong>(testid000)');
document.write('			<a href="#" class="btn_logout">로그아웃</a></a>');
document.write('		</div -->');
document.write('		<!-- //로그인 후 -->');
document.write('		<div class="section">');
document.write('			<ul class="lst_totalmenu">');
document.write('				<li>');
document.write('					<a href="#none">마이페이지</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">마이씽/쿠폰</a></li>');
document.write('						<li><a href="#">마이신사고 도서</a></li>');
document.write('						<li><a href="#">장바구니</a></li>');
document.write('						<li><a href="#">주문/배송조회</a></li>');
document.write('						<li><a href="#">1:1 문의 내역</a></li>');
document.write('						<li><a href="#">회원정보수정</a></li>');
document.write('						<li><a href="#">회원탈퇴</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li class="on">');
document.write('					<a href="#none">신사고도서</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">고등 참고서</a></li>');
document.write('						<li><a href="#">중등 참고서</a></li>');
document.write('						<li><a href="#">초등 참고서</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="#none">학습자료실</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">고등 자료실</a></li>');
document.write('						<li><a href="#">중등 자료실</a></li>');
document.write('						<li><a href="#">초등 자료실</a></li>');
document.write('						<li><a href="#">교과서 자료실</a></li>');
document.write('						<li><a href="#">도서학습자료</a></li>');
document.write('						<li><a href="#">스노우공모전</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="#none">나.바.힘</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">카툰Feel</a></li>');
document.write('						<li><a href="#">선물상자</a></li>');
document.write('						<li><a href="#">희망나침반</a></li>');
document.write('						<li><a href="#">희망우체통</a></li>');
document.write('						<li><a href="#">내가 쓰는 나바힘</a></li>');
document.write('						<li><a href="#">신사고 멘토링</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="#none">씽라운지</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">씽안내</a></li>');
document.write('						<li><a href="#">씽등록</a></li>');
document.write('						<li><a href="#">씽몰</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="#none">이벤트</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">진행중 이벤트</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="#none">고객센터</a>');
document.write('					<ul class="lst_totalmenu_depth2">');
document.write('						<li><a href="#">공지사항</a></li>');
document.write('						<li><a href="#">FAQ</a></li>');
document.write('						<li><a href="#">1:1문의</a></li>');
document.write('						<li><a href="#">회원탈퇴</a></li>');
document.write('					</ul>');
document.write('				</li>');
document.write('			</ul>');
document.write('		</div>');
document.write('		<div class="group_familysite">');
document.write('			<ul class="lst_familysite">');
document.write('				<li><a href="#" target="_blank" title="새창"><span class="ico ico_family"></span>우공비맘</a><li>');
document.write('				<li><a href="#" target="_blank" title="새창"><span class="ico ico_family v2"></span>모바일러닝</a><li>');
document.write('				<li><a href="#" target="_blank" title="새창"><span class="ico ico_family v3"></span>신사고 공식 블로그</a><li>');
document.write('				<li><a href="#" target="_blank" title="새창"><span class="ico ico_family v4"></span>English Sinsago</a><li>');
document.write('			</ul>');
document.write('		</div>');
document.write('		<p class="loc_lftmenu_close"><a href="#none" class="btn btn_lftmenu_close">닫기</a></p>');
document.write('	</div><!-- //전체메뉴 -->');
document.write('	<span class="bg_deemed"><a href="#"></a></span>');	
document.write('</header><!-- //header -->');