document.write('<footer><!-- footer -->');
document.write('	<div class="group_usermenu">');
document.write('		<h3 class="blind">사용자 메뉴</h3>');
document.write('		<ul class="lst_usermenu">');
document.write('			<li><a href="#">로그아웃</a></li>');
document.write('			<li><a href="#">마이페이지</a></li>');
document.write('			<li><a href="#">PC 버전</a></li>');
document.write('			<li><a href="#">고객센터</a></li>');
document.write('		</ul>');
document.write('	</div>');
document.write('	<div>');
document.write('		<h3 class="blind">사이드 메뉴</h3>');
document.write('		<ul class="lst_sidemenu">');
document.write('			<li><a href="#">회사소개</a></li>');
document.write('			<li><a href="#">이용약관</a></li>');
document.write('			<li><a href="#">개인정보처리방침</a></li>');
document.write('		</ul>');
document.write('	</div>');
document.write('	<address>Copyright ⓒ (주)좋은책신사고 All rights reserved.</address>');
document.write('	<p class="loc_top"><a href="#none" class="btn_top">TOP</a></p>');
document.write('</footer><!-- //footer -->');